mythril.mythril.mythril_analyzer [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/instructions.py", line 1168, in extcodesize_
    addr = hex(helper.get_concrete_int(addr))
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/util.py", line 109, in get_concrete_int
    raise TypeError("Got a symbolic BitVecRef")
TypeError: Got a symbolic BitVecRef

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 579, in indent
    return IndentFormatObject(i, arg)
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mythril/mythril/mythril_analyzer.py", line 153, in fire_lasers
    sym = SymExecWrapper(
  File "/usr/local/lib/python3.10/dist-packages/mythril/analysis/symbolic.py", line 191, in __init__
    self.laser.sym_exec(
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/svm.py", line 206, in sym_exec
    self.execute_transactions(created_account.address)
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/svm.py", line 232, in execute_transactions
    self._execute_transactions_incremental(
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/svm.py", line 302, in _execute_transactions_incremental
    execute_message_call(self, address, func_hashes=func_hashes)
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/transaction/symbolic.py", line 151, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/svm.py", line 344, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/svm.py", line 445, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/instructions.py", line 265, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/instructions.py", line 196, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/instructions.py", line 131, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/ethereum/instructions.py", line 1171, in extcodesize_
    state.stack.append(global_state.new_bitvec("extcodesize_" + str(addr), 256))
  File "/usr/local/lib/python3.10/dist-packages/mythril/laser/smt/expression.py", line 49, in __repr__
    return repr(self.raw)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3.py", line 362, in __repr__
    return obj_to_string(self)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1434, in obj_to_string
    _PP(out, _Formatter(a))
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1327, in __call__
    return self.main(a)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1301, in main
    return self.pp_expr(a, 0, [])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1198, in pp_expr
    return self.pp_app(a, d, xs)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1167, in pp_app
    return self.pp_prefix(a, d, xs)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 928, in pp_prefix
    r.append(self.pp_expr(child, d + 1, xs))
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1198, in pp_expr
    return self.pp_app(a, d, xs)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1167, in pp_app
    return self.pp_prefix(a, d, xs)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 928, in pp_prefix
    r.append(self.pp_expr(child, d + 1, xs))
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1198, in pp_expr
    return self.pp_app(a, d, xs)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 1163, in pp_app
    return self.pp_infix(a, d, xs)
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 988, in pp_infix
    return group(seq(self.infix_args(a, d, xs), op))
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 583, in group
    return ChoiceFormatObject([arg.flat(), arg])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 500, in flat
    return self.children[0].flat()
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 519, in flat
    return indent(self.indent, self.child.flat())
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 519, in flat
    return indent(self.indent, self.child.flat())
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 519, in flat
    return indent(self.indent, self.child.flat())
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 519, in flat
    return indent(self.indent, self.child.flat())
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in <listcomp>
    return compose([a.flat() for a in self.children])
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 519, in flat
    return indent(self.indent, self.child.flat())
  File "/usr/local/lib/python3.10/dist-packages/z3_solver-4.12.0.0-py3.10-linux-x86_64.egg/z3/z3printer.py", line 486, in flat
    return compose([a.flat() for a in self.children])
MemoryError

{"error": null, "issues": [], "success": true}
